
patches:
- path: replicas.yaml
- path: configmap.yaml

configMapGenerator:
- envs:
  - config.properties
  name: mykustom-map
#- files:
#    - test.txt
#  name: mykustom-text
#  behavior: replace
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
